import ApiNavigation from '@/components/ApiNavigation';
import Pagination from '@/components/Pagination';
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home(props) {
	const { pageCount, posts, currentPage } = props;

	const router = useRouter();

	const paginationHandler = (page) => {
		const currentPath = router.pathname;
		let currentQuery = router.query;

		currentQuery.page = page.selected + 1;
		console.log(currentQuery.page);

		router.push({
			pathname: currentPath,
			query: currentQuery
		});
	};

	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex  flex-col items-center justify-between ">
				<p className="lg:text-5xl md:text-5xl text-4xl mt-20 p-10">
					Pagination and Swiper in TailwindCSS with Next.js
				</p>
				<Pagination
					pageCount={pageCount}
					currentPage={currentPage}
					paginationHandler={paginationHandler}
				/>
				<ApiNavigation posts={posts} />
			</main>
		</>
	);
}
export const getServerSideProps = async ({ query }) => {
	const page = query?.page || 1;

	const { data } = await axios.get(
		`https://rickandmortyapi.com/api/character?page=${page}`
	);

	return {
		props: {
			pageCount: data.info.pages,
			posts: data.results,
			currentPage: page
		}
	};
};
